# ASSIGNMENT DAY 34 - SOCIAL MEDIA ANALYTICS
**Putri Dyra Adlina Syifa**

## UPLOAD DATA

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_sosmed = pd.read_csv('/content/drive/MyDrive/DIBIMBING/Assignment/social_media_engagement.csv')
df_sosmed.head()

,Content_ID,Platform,Content_Type,Reach,Impressions,Likes,Comments,Shares,Saves,Clicks,Upload_Time,Day_of_Week,Hashtags_Count,Video_Duration_Sec,Caption_Length,Follower_Count,Ad_Spend_USD,Is_Promoted,Completion_Rate,View_Through_Rate,CTR,Engagement_Rate_Reach,Engagement_Rate_Impressions
0,C001,YouTube,Single Image,1860,7350,116,7,6,NaN,121,Night,Wed,1,NaN,353,199027,157,1,0.00,0.99,0.016463,0.069355,0.017551
1,C002,Instagram,Single Image,86305,92801,2568,475,187,189.0,2734,Morning,Wed,6,NaN,30,261840,166,1,0.95,0.97,0.029461,0.039615,0.036842
2,C003,TikTok,Short Video,77552,80264,7051,1363,91,NaN,5486,Morning,Thu,17,6.0,399,245181,105,1,0.18,0.97,0.068349,0.109668,0.105963
3,C004,TikTok,Single Image,66697,355470,1991,269,303,NaN,7629,Afternoon,Sun,12,NaN,50,43044,14,0,0.07,0.99,0.107309,0.038428,0.036051
4,C005,X/Twitter,Reels,68563,71358,1505,62,138,NaN,5618,Evening,Tue,8,NaN,37,289806,71,1,0.33,0.06,0.078730,0.024868,0.023894

In [ ]:
df_sosmed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Content_ID                   100 non-null    object
 1   Platform                     100 non-null    object
 2   Content_Type                 100 non-null    object
 3   Reach                        100 non-null    int64
 4   Impressions                  100 non-null    int64
 5   Likes                        100 non-null    int64
 6   Comments                     100 non-null    int64
 7   Shares                       100 non-null    int64
 8   Saves                        22 non-null     float64
 9   Clicks                       100 non-null    int64
 10  Upload_Time                  100 non-null    object
 11  Day_of_Week                  100 non-null    object
 12  Hashtags_Count               100 non-null    int64
 13  Video_Duration_Sec           40 non-null     float64
 14  Caption_Length               100 non-null    int64
 15  Follower_Count               100 non-null    int64
 16  Ad_Spend_USD                 100 non-null    int64
 17  Is_Promoted                  100 non-null    int64
 18  Completion_Rate              100 non-null    float64
 19  View_Through_Rate            100 non-null    float64
 20  CTR                          100 non-null    float64
 21  Engagement_Rate_Reach        100 non-null    float64
 22  Engagement_Rate_Impressions  100 non-null    float64
dtypes: float64(7), int64(11), object(5)
memory usage: 18.1+ KB

In [ ]:
df_sosmed.isnull().sum()

Content_ID                      0
Platform                        0
Content_Type                    0
Reach                           0
Impressions                     0
Likes                           0
Comments                        0
Shares                          0
Saves                          78
Clicks                          0
Upload_Time                     0
Day_of_Week                     0
Hashtags_Count                  0
Video_Duration_Sec             60
Caption_Length                  0
Follower_Count                  0
Ad_Spend_USD                    0
Is_Promoted                     0
Completion_Rate                 0
View_Through_Rate               0
CTR                             0
Engagement_Rate_Reach           0
Engagement_Rate_Impressions     0
dtype: int64

Terdapat data kosong yaitu kolom Saves dengan total 78 data dan Video_Duration_Sec dengan total 60 data.

In [ ]:
df_sosmed["Platform"].value_counts()

Platform
X/Twitter    28
TikTok       26
YouTube      24
Instagram    22
Name: count, dtype: int64

In [ ]:
df_sosmed["Content_Type"].value_counts()

Content_Type
Shorts          18
Short Video     14
Thread          14
Reels           14
Single Image    13
Carousel        11
Long Video       8
Text + Image     8
Name: count, dtype: int64

## IDENTIFIKASI KOMPONEN PENTING

In [ ]:
engagement_columns = [
    "Content_ID",
    "Platform",
    "Content_Type",
    "Reach",
    "Impressions",
    "Likes",
    "Comments",
    "Shares",
    "Saves",
    "Clicks"]

df_sosmed[engagement_columns].head()

,Content_ID,Platform,Content_Type,Reach,Impressions,Likes,Comments,Shares,Saves,Clicks
0,C001,YouTube,Single Image,1860,7350,116,7,6,NaN,121
1,C002,Instagram,Single Image,86305,92801,2568,475,187,189.0,2734
2,C003,TikTok,Short Video,77552,80264,7051,1363,91,NaN,5486
3,C004,TikTok,Single Image,66697,355470,1991,269,303,NaN,7629
4,C005,X/Twitter,Reels,68563,71358,1505,62,138,NaN,5618

In [ ]:
df_sosmed["Saves"] = df_sosmed["Saves"].fillna(0)
df_sosmed["Saves"].isnull().sum()

np.int64(0)

In [ ]:
df_sosmed.duplicated().sum()

np.int64(0)

In [ ]:
df_sosmed[engagement_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Content_ID    100 non-null    object
 1   Platform      100 non-null    object
 2   Content_Type  100 non-null    object
 3   Reach         100 non-null    int64
 4   Impressions   100 non-null    int64
 5   Likes         100 non-null    int64
 6   Comments      100 non-null    int64
 7   Shares        100 non-null    int64
 8   Saves         100 non-null    float64
 9   Clicks        100 non-null    int64
dtypes: float64(1), int64(6), object(3)
memory usage: 7.9+ KB

In [ ]:
df_sosmed.groupby("Platform")["Saves"].apply(
    lambda x: (x > 0).sum())

Platform
Instagram    21
TikTok        0
X/Twitter     0
YouTube       0
Name: Saves, dtype: int64

In [ ]:
df_sosmed[df_sosmed["Platform"] == "Instagram"]["Saves"].count()

np.int64(22)

In [ ]:
df_sosmed[
    ["Reach",
        "Impressions",
        "Likes",
        "Comments",
        "Shares",
        "Saves",
        "Clicks"
    ]].describe()

,Reach,Impressions,Likes,Comments,Shares,Saves,Clicks
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,47340.530000,74943.500000,6691.040000,276.71000,218.690000,82.890000,4577.560000
std,34622.233595,75738.496049,23328.320336,324.42083,256.824497,253.179694,5691.959715
min,-34933.000000,4744.000000,15.000000,1.00000,0.000000,0.000000,3.000000
25%,19685.500000,33612.250000,681.750000,43.00000,24.750000,0.000000,1238.000000
50%,44089.500000,61301.500000,2127.500000,145.50000,116.500000,0.000000,3092.500000
75%,80976.750000,94231.250000,4231.750000,363.25000,294.750000,0.000000,6158.250000
max,99142.000000,559530.000000,192546.000000,1363.00000,1008.000000,1624.000000,42287.000000

### Check dan Handling Kolom Reach

In [ ]:
df_sosmed[df_sosmed["Reach"] <= 0][
    ["Content_ID", "Reach", "Impressions", "Likes", "Comments", "Shares", "Clicks"]]

   Content_ID  Reach  Impressions  Likes  Comments  Shares  Clicks
14       C015  -6600        14696    525        34      63    1072
24       C025  -1728        19577    150        26      18    2224
41       C042 -10111        15553     15         1       1       3
61       C062 -28935        33908   1049       198     144     390
64       C065 -34933        37066   2381       145     292     431
65       C066 -30757        32725   2283       152     198    2611
83       C084 -14760        27448    928        46      30    3081

In [ ]:
check_reach = df_sosmed[df_sosmed["Reach"] < 0].copy()

check_reach["Reach_Positive"] = check_reach["Reach"].abs()

check_reach["Total_Interactions"] = (
    check_reach["Likes"]
    + check_reach["Comments"]
    + check_reach["Shares"]
    + check_reach["Saves"].fillna(0))

check_reach["ER_Recalculated"] = (
    check_reach["Total_Interactions"]
    / check_reach["Reach_Positive"])

check_reach[[  "Content_ID",
               "Reach",
               "Reach_Positive",
               "Impressions",
               "Total_Interactions",
               "ER_Recalculated",
               "Engagement_Rate_Reach"]]

,Content_ID,Reach,Reach_Positive,Impressions,Total_Interactions,ER_Recalculated,Engagement_Rate_Reach
14,C015,-6600,6600,14696,622.0,0.094242,0.094242
24,C025,-1728,1728,19577,194.0,0.112269,0.112269
41,C042,-10111,10111,15553,19.0,0.001879,0.001879
61,C062,-28935,28935,33908,1476.0,0.051011,0.051011
64,C065,-34933,34933,37066,2818.0,0.080669,0.080669
65,C066,-30757,30757,32725,2633.0,0.085607,0.085607
83,C084,-14760,14760,27448,1004.0,0.068022,0.068022

In [ ]:
df_sosmed["Reach"] = df_sosmed["Reach"].abs()

### Check dan Handling Kolom Impressions

In [ ]:
df_sosmed[df_sosmed["Impressions"] <= 0]

Empty DataFrame
Columns: [Content_ID, Platform, Content_Type, Reach, Impressions, Likes, Comments, Shares, Saves, Clicks, Upload_Time, Day_of_Week, Hashtags_Count, Video_Duration_Sec, Caption_Length, Follower_Count, Ad_Spend_USD, Is_Promoted, Completion_Rate, View_Through_Rate, CTR, Engagement_Rate_Reach, Engagement_Rate_Impressions]
Index: []

In [ ]:
df_sosmed[df_sosmed["Reach"].abs() > df_sosmed["Impressions"]][["Content_ID", "Reach", "Impressions"]]

Empty DataFrame
Columns: [Content_ID, Reach, Impressions]
Index: []

In [ ]:
Q1 = df_sosmed["Impressions"].quantile(0.25)
Q3 = df_sosmed["Impressions"].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + 1.5 * IQR

print("Batas atas:", upper_limit)

impressions_outlier = df_sosmed[
    df_sosmed["Impressions"] > upper_limit]

impressions_outlier[
    ["Content_ID", "Reach", "Impressions", "Clicks", "CTR"]]

Batas atas: 185159.75

   Content_ID  Reach  Impressions  Clicks       CTR
3        C004  66697       355470    7629  0.107309
17       C018  94848       559530    7509  0.067101
18       C019  33093       186675     635  0.017008
50       C051  42914       239925    1990  0.041471
76       C077  63046       357515    2043  0.028572
81       C082  40443       207490    4703  0.113331

In [ ]:
check_impressions = impressions_outlier.copy()

check_impressions["Total_Interactions"] = (
    check_impressions["Likes"]
    + check_impressions["Comments"]
    + check_impressions["Shares"]
    + check_impressions["Saves"].fillna(0))

check_impressions["CTR_Recalculated"] = (
    check_impressions["Clicks"]
    / check_impressions["Impressions"])

check_impressions["ER_Impressions_Recalculated"] = (
    check_impressions["Total_Interactions"]
    / check_impressions["Impressions"])

check_impressions[[
        "Content_ID",
        "Impressions",
        "CTR",
        "CTR_Recalculated",
        "Engagement_Rate_Impressions",
        "ER_Impressions_Recalculated"]]

,Content_ID,Impressions,CTR,CTR_Recalculated,Engagement_Rate_Impressions,ER_Impressions_Recalculated
3,C004,355470,0.107309,0.021462,0.036051,0.007210
17,C018,559530,0.067101,0.013420,0.012189,0.002438
18,C019,186675,0.017008,0.003402,0.095380,0.019076
50,C051,239925,0.041471,0.008294,0.028967,0.005793
76,C077,357515,0.028572,0.005714,0.025216,0.005043
81,C082,207490,0.113331,0.022666,0.058653,0.011731

In [ ]:
check_impressions["Impressions_Adjusted"] = (
    check_impressions["Impressions"] / 5)

check_impressions["CTR_Adjusted"] = (
    check_impressions["Clicks"]
    / check_impressions["Impressions_Adjusted"])

check_impressions["ER_Adjusted"] = (
    check_impressions["Total_Interactions"]
    / check_impressions["Impressions_Adjusted"])

check_impressions[[
        "Content_ID",
        "Impressions",
        "Impressions_Adjusted",
        "CTR",
        "CTR_Adjusted",
        "Engagement_Rate_Impressions",
        "ER_Adjusted" ]]

,Content_ID,Impressions,Impressions_Adjusted,CTR,CTR_Adjusted,Engagement_Rate_Impressions,ER_Adjusted
3,C004,355470,71094.0,0.107309,0.107309,0.036051,0.036051
17,C018,559530,111906.0,0.067101,0.067101,0.012189,0.012189
18,C019,186675,37335.0,0.017008,0.017008,0.095380,0.095380
50,C051,239925,47985.0,0.041471,0.041471,0.028967,0.028967
76,C077,357515,71503.0,0.028572,0.028572,0.025216,0.025216
81,C082,207490,41498.0,0.113331,0.113331,0.058653,0.058653

In [ ]:
df_sosmed.loc[check_impressions.index,
    "Impressions"] = (
    check_impressions["Impressions_Adjusted"]
    .round()
    .astype(int))

### Check dan Handling Kolom Likes

In [ ]:
check_likes = df_sosmed[
    df_sosmed["Likes"] > df_sosmed["Reach"]].copy()

check_likes[[
        "Content_ID",
        "Reach",
        "Impressions",
        "Likes",
        "Comments",
        "Shares",
        "Saves",
        "Engagement_Rate_Reach",
        "Engagement_Rate_Impressions" ]]

,Content_ID,Reach,Impressions,Likes,Comments,Shares,Saves,Engagement_Rate_Reach,Engagement_Rate_Impressions
12,C013,13183,26157,52314,19,2,0.0,0.010165,0.005123
49,C050,54173,58935,117870,910,660,968.0,0.139904,0.128599
67,C068,84300,96273,192546,104,183,0.0,0.018826,0.016484
72,C073,24821,29720,59440,28,75,0.0,0.032190,0.026884

In [ ]:
check_likes["Total_Interaction_From_ER"] = (
    check_likes["Engagement_Rate_Reach"]
    * check_likes["Reach"]).round()

check_likes["Likes_Corrected"] = (
    check_likes["Total_Interaction_From_ER"]
    - check_likes["Comments"]
    - check_likes["Shares"]
    - check_likes["Saves"])

check_likes[[
        "Content_ID",
        "Likes",
        "Total_Interaction_From_ER",
        "Comments",
        "Shares",
        "Saves",
        "Likes_Corrected"]]

,Content_ID,Likes,Total_Interaction_From_ER,Comments,Shares,Saves,Likes_Corrected
12,C013,52314,134.0,19,2,0.0,113.0
49,C050,117870,7579.0,910,660,968.0,5041.0
67,C068,192546,1587.0,104,183,0.0,1300.0
72,C073,59440,799.0,28,75,0.0,696.0

In [ ]:
df_sosmed["Likes_Original"] = df_sosmed["Likes"]

In [ ]:
likes_error = df_sosmed["Likes"] > df_sosmed["Reach"]

total_interaction_corrected = (
    df_sosmed.loc[likes_error, "Engagement_Rate_Reach"]
    * df_sosmed.loc[likes_error, "Reach"]).round()

likes_corrected = (
    total_interaction_corrected
    - df_sosmed.loc[likes_error, "Comments"]
    - df_sosmed.loc[likes_error, "Shares"]
    - df_sosmed.loc[likes_error, "Saves"])

In [ ]:
df_sosmed[df_sosmed["Likes_Original"] != df_sosmed["Likes"]][
    ["Content_ID", "Likes_Original", "Likes"]]

Empty DataFrame
Columns: [Content_ID, Likes_Original, Likes]
Index: []

In [ ]:
df_sosmed.loc[check_likes.index,
    "Likes"] = (
    check_likes["Likes_Corrected"]
    .round()
    .astype(int))

### Check dan Handling Kolom Clicks

In [ ]:
check_clicks = df_sosmed[
    df_sosmed["Clicks"] > df_sosmed["Impressions"]].copy()

check_clicks[[
        "Content_ID",
        "Impressions",
        "Clicks",
        "CTR"]]

   Content_ID  Impressions  Clicks       CTR
7        C008        40981   42287  0.031868
72       C073        29720   30482  0.025639

In [ ]:
check_clicks["Clicks_From_CTR"] = (
    check_clicks["CTR"]
    * check_clicks["Impressions"]).round()

check_clicks["Clicks_Minus_Impressions"] = (
    check_clicks["Clicks"]
    - check_clicks["Impressions"])

check_clicks[[
        "Content_ID",
        "Impressions",
        "Clicks",
        "CTR",
        "Clicks_From_CTR",
        "Clicks_Minus_Impressions"]]

,Content_ID,Impressions,Clicks,CTR,Clicks_From_CTR,Clicks_Minus_Impressions
7,C008,40981,42287,0.031868,1306.0,1306
72,C073,29720,30482,0.025639,762.0,762

In [ ]:
df_sosmed["Clicks_Original"] = df_sosmed["Clicks"]

In [ ]:
clicks_error = df_sosmed["Clicks"] > df_sosmed["Impressions"]

df_sosmed.loc[clicks_error, "Clicks"] = (
    df_sosmed.loc[clicks_error, "CTR"]
    * df_sosmed.loc[clicks_error, "Impressions"]).round().astype(int)

In [ ]:
df_sosmed[df_sosmed["Clicks_Original"] != df_sosmed["Clicks"]][["Content_ID", "Clicks_Original", "Clicks"]]

   Content_ID  Clicks_Original  Clicks
7        C008            42287    1306
72       C073            30482     762

### Check Kolom Comments dan Shares

In [ ]:
df_sosmed[
    df_sosmed["Comments"].isna()
    | df_sosmed["Shares"].isna()
    | (df_sosmed["Comments"] < 0)
    | (df_sosmed["Shares"] < 0)]

Empty DataFrame
Columns: [Content_ID, Platform, Content_Type, Reach, Impressions, Likes, Comments, Shares, Saves, Clicks, Upload_Time, Day_of_Week, Hashtags_Count, Video_Duration_Sec, Caption_Length, Follower_Count, Ad_Spend_USD, Is_Promoted, Completion_Rate, View_Through_Rate, CTR, Engagement_Rate_Reach, Engagement_Rate_Impressions, Likes_Original, Clicks_Original]
Index: []

## PERHITUNGAN METRIK

In [ ]:
df_sosmed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Content_ID                   100 non-null    object
 1   Platform                     100 non-null    object
 2   Content_Type                 100 non-null    object
 3   Reach                        100 non-null    int64
 4   Impressions                  100 non-null    int64
 5   Likes                        100 non-null    int64
 6   Comments                     100 non-null    int64
 7   Shares                       100 non-null    int64
 8   Saves                        100 non-null    float64
 9   Clicks                       100 non-null    int64
 10  Upload_Time                  100 non-null    object
 11  Day_of_Week                  100 non-null    object
 12  Hashtags_Count               100 non-null    int64
 13  Video_Duration_Sec           40 non-null     float64
 14  Caption_Length               100 non-null    int64
 15  Follower_Count               100 non-null    int64
 16  Ad_Spend_USD                 100 non-null    int64
 17  Is_Promoted                  100 non-null    int64
 18  Completion_Rate              100 non-null    float64
 19  View_Through_Rate            100 non-null    float64
 20  CTR                          100 non-null    float64
 21  Engagement_Rate_Reach        100 non-null    float64
 22  Engagement_Rate_Impressions  100 non-null    float64
 23  Likes_Original               100 non-null    int64
 24  Clicks_Original              100 non-null    int64
dtypes: float64(7), int64(13), object(5)
memory usage: 19.7+ KB

### Total Interactions
Total Interactions = Likes + Comments + Shares + Saves

Digunakan untuk menghitung seluruh interaksi utama yang diterima konten.

In [ ]:
df_sosmed["Total_Interactions"] = (
    df_sosmed["Likes"]
    + df_sosmed["Comments"]
    + df_sosmed["Shares"]
    + df_sosmed["Saves"]).astype(int)

In [ ]:
rename_columns = {}

if "CTR" in df_sosmed.columns:
    rename_columns["CTR"] = "CTR_Source"

if "Engagement_Rate_Reach" in df_sosmed.columns:
    rename_columns["Engagement_Rate_Reach"] = "IPR_Source"

if "Engagement_Rate_Impressions" in df_sosmed.columns:
    rename_columns["Engagement_Rate_Impressions"] = "IPI_Source"

df_sosmed.rename(columns=rename_columns, inplace=True)

In [ ]:
df_sosmed.columns

Index(['Content_ID', 'Platform', 'Content_Type', 'Reach', 'Impressions',
       'Likes', 'Comments', 'Shares', 'Saves', 'Clicks', 'Upload_Time',
       'Day_of_Week', 'Hashtags_Count', 'Video_Duration_Sec', 'Caption_Length',
       'Follower_Count', 'Ad_Spend_USD', 'Is_Promoted', 'Completion_Rate',
       'View_Through_Rate', 'CTR_Source', 'IPR_Source', 'IPI_Source',
       'Likes_Original', 'Clicks_Original', 'Total_Interactions'],
      dtype='object')

### Engagement Rate
ER = Total Interactions / Follower Count × 100%

Digunakan untuk mengukur interaksi konten dibandingkan jumlah followers akun.

In [ ]:
# Engagement Rate berdasarkan followers
df_sosmed["ER"] = (
    df_sosmed["Total_Interactions"]
    / df_sosmed["Follower_Count"])

### Interaction per Reach
IPR = Total Interactions / Reach × 100%

Digunakan untuk mengukur persentase interaksi dari pengguna unik yang melihat konten.

In [ ]:
# Interaction per Reach
df_sosmed["IPR"] = (
    df_sosmed["Total_Interactions"]
    / df_sosmed["Reach"])

### Interaction per Impression
IPI = Total Interactions / Impressions × 100%

Digunakan untuk mengukur interaksi dibandingkan seluruh frekuensi penayangan konten.

In [ ]:
# Interaction per Impression
df_sosmed["IPI"] = (
    df_sosmed["Total_Interactions"]
    / df_sosmed["Impressions"])

### Click-Through Rate
CTR = Clicks / Impressions × 100%

Digunakan untuk mengukur persentase impressions yang menghasilkan klik.

In [ ]:
# Click-Through Rate
df_sosmed["CTR"] = (
    df_sosmed["Clicks"]
    / df_sosmed["Impressions"])

In [ ]:
result_columns = [
    "Content_ID",
    "Platform",
    "Content_Type",
    "Total_Interactions",
    "ER",
    "IPR",
    "IPI",
    "CTR"]

df_sosmed[result_columns].head(10).style.format({
    "ER": "{:.2%}",
    "IPR": "{:.2%}",
    "IPI": "{:.2%}",
    "CTR": "{:.2%}"})

### Perhitungan Metrik Manual

In [ ]:
powerbi_columns = [
    "Content_ID",
    "Platform",
    "Content_Type",
    "Upload_Time",
    "Day_of_Week",
    "Reach",
    "Impressions",
    "Likes",
    "Comments",
    "Shares",
    "Saves",
    "Clicks",
    "Hashtags_Count",
    "Video_Duration_Sec",
    "Caption_Length",
    "Follower_Count",
    "Ad_Spend_USD",
    "Is_Promoted",
    "Completion_Rate",
    "View_Through_Rate",
    "Total_Interactions",
    "ER",
    "IPR",
    "IPI",
    "CTR"]

pd.set_option("display.max_columns", None)

display(df_sosmed[powerbi_columns].head(5))

,Content_ID,Platform,Content_Type,Upload_Time,Day_of_Week,Reach,Impressions,Likes,Comments,Shares,Saves,Clicks,Hashtags_Count,Video_Duration_Sec,Caption_Length,Follower_Count,Ad_Spend_USD,Is_Promoted,Completion_Rate,View_Through_Rate,Total_Interactions,ER,IPR,IPI,CTR
0,C001,YouTube,Single Image,Night,Wed,1860,7350,116,7,6,0.0,121,1,NaN,353,199027,157,1,0.00,0.99,129,0.000648,0.069355,0.017551,0.016463
1,C002,Instagram,Single Image,Morning,Wed,86305,92801,2568,475,187,189.0,2734,6,NaN,30,261840,166,1,0.95,0.97,3419,0.013058,0.039615,0.036842,0.029461
2,C003,TikTok,Short Video,Morning,Thu,77552,80264,7051,1363,91,0.0,5486,17,6.0,399,245181,105,1,0.18,0.97,8505,0.034689,0.109668,0.105963,0.068349
3,C004,TikTok,Single Image,Afternoon,Sun,66697,71094,1991,269,303,0.0,7629,12,NaN,50,43044,14,0,0.07,0.99,2563,0.059544,0.038428,0.036051,0.107309
4,C005,X/Twitter,Reels,Evening,Tue,68563,71358,1505,62,138,0.0,5618,8,NaN,37,289806,71,1,0.33,0.06,1705,0.005883,0.024868,0.023894,0.078730

## SAVE NEW FILE

In [ ]:
from google.colab import files

df_sosmed[powerbi_columns].to_csv('social_media_engagement_clean.csv', index=False)
files.download('social_media_engagement_clean.csv')